version: '3.8'

services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    pull_policy: "always"
    restart: "always"
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./questdb_root:/root/.questdb
    networks:
      - questdb-network

networks:
  questdb-network:
    name: questdb-network
    driver: bridge
