name: compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install poetry
      uses: Gr1N/setup-poetry@v7
    - name: install dependencies
      run: make install-dependencies-dev
    - name: compose up
      run: make compose-up
    - name: check questdb
      run: curl 127.0.0.1:9000
    - name: compose down
      run: make compose-down
