name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install poetry
      uses: Gr1N/setup-poetry@v7
    - name: install dependencies
      run: make install-dependencies-dev
    - name: check format
      run: make format-code
    - name: start docker
      run: make compose-up
    - name: run tests
      run: make test
    - name: stop docker
      run: make compose-down
